    # image: ahmedkhalaf666/grpc-docker-server
    # image: ahmedkhalaf666/grpc-docker-client
version: '3'
services:
  server:
    build:
      context: ahmedkhalaf666/grpc-docker-server
      dockerfile: Dockerfile
    ports:
      - "5001:80"  # Map container port 80 to host port 5001

  client:
    build:
      context: ahmedkhalaf666/grpc-docker-client
      dockerfile: Dockerfile
    ports:
      - "5002:80"  # Map container port 80 to host port 5002
    depends_on:
       - server