name: test-build-deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  DOCKER_REPO_BACK_SERVER: "grpc-docker-server"
  DOCKER_REPO_BACK_CLIENT: "grpc-docker-client"
  DOCKER_TAG: "latest"

jobs: 
  build_deploy_to_docker:
    name: Build-and-deploy-to-docker-hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
   
    - name: Build server Api the Docker iamge 
      run: docker build . --file server/Dockerfile --tag  ${{secrets.DOCKER_USER}}/$DOCKER_REPO_BACK_SERVER:$DOCKER_TAG
    - name: Docker Push 
      run: docker push ${{secrets.DOCKER_USER}}/$DOCKER_REPO_BACK_SERVER:$DOCKER_TAG


   
    - name: Build client Chat the Docker iamge 
      run: docker build . --file client/Dockerfile --tag  ${{secrets.DOCKER_USER}}/$DOCKER_REPO_BACK_CLIENT:$DOCKER_TAG
    - name: Docker Push 
      run: docker push ${{secrets.DOCKER_USER}}/$DOCKER_REPO_BACK_CLIENT:$DOCKER_TAG


